"""Source-traceable rules from the supplied Saju Master prompt v2.0.

Tables reproduce sections 1.2.4/9/14/15. Numerical weights, strength thresholds
and the projection onto lottery numbers are this application's heuristics,
NOT classical standards, probabilities, or empirically validated predictions.
"""
from __future__ import annotations

from collections import Counter
from itertools import combinations
from typing import Any

STEMS = "甲乙丙丁戊己庚辛壬癸"
BRANCHES = "子丑寅卯辰巳午未申酉戌亥"
ELEMENTS = ("wood", "fire", "earth", "metal", "water")
KO = dict(zip(ELEMENTS, ("목", "화", "토", "금", "수"), strict=True))
GENERATES = dict(zip(ELEMENTS, ELEMENTS[1:] + ELEMENTS[:1], strict=True))
CONTROLS = dict(zip(ELEMENTS, ELEMENTS[2:] + ELEMENTS[:2], strict=True))
# Explicit source ratios, keyed by stem rather than library array order.
HIDDEN = {
    "子": {"癸": 1.0}, "丑": {"癸": .30, "辛": .10, "己": .60},
    "寅": {"戊": .23, "丙": .23, "甲": .54}, "卯": {"乙": 1.0},
    "辰": {"乙": .30, "癸": .10, "戊": .60},
    "巳": {"戊": .23, "庚": .23, "丙": .54}, "午": {"己": .30, "丁": .70},
    "未": {"丁": .30, "乙": .10, "己": .60},
    "申": {"戊": .23, "壬": .23, "庚": .54}, "酉": {"辛": 1.0},
    "戌": {"辛": .30, "丁": .10, "戊": .60},
    "亥": {"戊": .23, "甲": .17, "壬": .60},
}
PRINCIPAL = {branch: max(hidden, key=hidden.get) for branch, hidden in HIDDEN.items()}
TEN_GODS = ("비견", "겁재", "식신", "상관", "편재", "정재", "편관", "정관", "편인", "정인")
STEM_HARMONY = {"甲己": "earth", "乙庚": "metal", "丙辛": "water", "丁壬": "wood", "戊癸": "fire"}
STEM_CLASH = ("甲庚", "乙辛", "丙壬", "丁癸")
SIX_HARMONY = {"子丑": "earth", "寅亥": "wood", "卯戌": "fire", "辰酉": "metal", "巳申": "water", "午未": None}
BRANCH_CLASH = ("子午", "丑未", "寅申", "卯酉", "辰戌", "巳亥")
BRANCH_BREAK = ("子酉", "午卯", "寅亥", "申巳", "辰丑", "戌未")
BRANCH_HARM = ("子未", "丑午", "寅巳", "卯辰", "申亥", "酉戌")
THREE_HARMONY = {"申子辰": "water", "亥卯未": "wood", "寅午戌": "fire", "巳酉丑": "metal"}
DIRECTION_HARMONY = {"寅卯辰": "wood", "巳午未": "fire", "申酉戌": "metal", "亥子丑": "water"}
THREE_PUNISHMENT = ("寅巳申", "丑戌未")
SELF_PUNISHMENT = "辰午酉亥"
SOURCE_RULE_VERSION = "saju_prompt_v2_application_v1"
APPLICATION_NOTICE = (
    "지장간 비율·십신·관계표는 제공 문서 기준입니다. 강약 임계값, 보완오행 합의 점수, "
    "운별 가중치와 1~45 끝자리/홀짝 배속은 자체 응용 규칙이며 당첨확률이 아닙니다. "
    "합의 존재만으로 합화나 길흉을 확정하지 않습니다."
)


def stem_element(stem: str) -> str:
    return ELEMENTS[STEMS.index(stem) // 2]


def ten_god(day_stem: str, other_stem: str) -> str:
    """All 100 combinations; source section 1.2.4's generative rule."""
    day, other = stem_element(day_stem), stem_element(other_stem)
    offset = (ELEMENTS.index(other) - ELEMENTS.index(day)) % 5
    same = STEMS.index(day_stem) % 2 == STEMS.index(other_stem) % 2
    # Generated by: offset 4; controlled by: offset 3.
    base = {0: 0, 1: 2, 2: 4, 3: 6, 4: 8}[offset]
    return TEN_GODS[base + int(not same)]


def number_stem(element: str, polarity: str) -> str:
    """Modern application: project HeTu element + odd/even onto one stem."""
    return STEMS[2 * ELEMENTS.index(element) + (polarity == "yin")]


def relations(pillars: dict[str, dict[str, Any]], required: str | None = None) -> list[dict[str, Any]]:
    """Find structural relations; never equate a combination with transformation.

    With required, only relations that involve that layer are returned. Counts
    retain pillar positions so self-punishment requires two distinct occurrences.
    """
    events: list[dict[str, Any]] = []
    items = list(pillars.items())

    def add(kind: str, positions: tuple[str, ...], symbols: str, element: str | None = None) -> None:
        if required is not None and required not in positions:
            return
        events.append({"kind": kind, "positions": list(positions), "symbols": symbols,
                       "element": element, "transformation_confirmed": False})

    for (ka, a), (kb, b) in combinations(items, 2):
        pos = (ka, kb)
        stems = frozenset((a["stem"], b["stem"]))
        branches = frozenset((a["branch"], b["branch"]))
        for symbols, element in STEM_HARMONY.items():
            if stems == frozenset(symbols):
                add("천간합", pos, symbols, element)
        for symbols in STEM_CLASH:
            if stems == frozenset(symbols):
                add("천간충", pos, symbols)
        for symbols, element in SIX_HARMONY.items():
            if branches == frozenset(symbols):
                add("육합", pos, symbols, element)
        for kind, groups in (("육충", BRANCH_CLASH), ("파", BRANCH_BREAK), ("해", BRANCH_HARM), ("자묘형", ("子卯",))):
            for symbols in groups:
                if branches == frozenset(symbols):
                    add(kind, pos, symbols)
        if a["branch"] == b["branch"] and a["branch"] in SELF_PUNISHMENT:
            add("자형", pos, a["branch"] * 2)
    for triple in combinations(items, 3):
        pos = tuple(key for key, _ in triple)
        symbols_set = frozenset(value["branch"] for _, value in triple)
        for kind, groups in (("삼합", THREE_HARMONY), ("방합", DIRECTION_HARMONY)):
            for symbols, element in groups.items():
                if symbols_set == frozenset(symbols):
                    add(kind, pos, symbols, element)
        for symbols in THREE_PUNISHMENT:
            if symbols_set == frozenset(symbols):
                add("삼형", pos, symbols)
    return events


def analyze_natal(pillars: dict[str, dict[str, Any]], day_stem: str) -> dict[str, Any]:
    """Source tables plus an explicit, inspectable application-level strength index."""
    day_element = stem_element(day_stem)
    resource = ELEMENTS[(ELEMENTS.index(day_element) - 1) % 5]
    roles = {"companion": day_element, "resource": resource,
             "output": GENERATES[day_element], "wealth": CONTROLS[day_element],
             "officer": ELEMENTS[(ELEMENTS.index(day_element) - 2) % 5]}
    counts = dict.fromkeys(ELEMENTS, 0.0)
    glyph_counts = dict.fromkeys(ELEMENTS, 0)
    gods = dict.fromkeys(TEN_GODS, 0.0)
    visible = [p["stem"] for key, p in pillars.items() if key != "day"]
    roots, exposed = [], []
    for key, pillar in pillars.items():
        stem, branch = pillar["stem"], pillar["branch"]
        glyph_counts[stem_element(stem)] += 1
        glyph_counts[stem_element(PRINCIPAL[branch])] += 1
        counts[stem_element(stem)] += 1.0
        if key != "day":
            gods[ten_god(day_stem, stem)] += 1.0
        branch_weight = 1.5 if key == "month" else 1.0
        hidden = HIDDEN[branch]
        for hidden_stem, fraction in hidden.items():
            counts[stem_element(hidden_stem)] += fraction * branch_weight
            gods[ten_god(day_stem, hidden_stem)] += fraction * branch_weight
            if stem_element(hidden_stem) == day_element:
                roots.append({"position": key, "stem": hidden_stem, "fraction": fraction})
            if hidden_stem in visible:
                exposed.append({"position": key, "stem": hidden_stem, "fraction": fraction})
        pillar["hidden_stem_ratios"] = dict(hidden)
        pillar["hidden_stems"] = list(hidden)
        pillar["ten_god_stem"] = "본원" if key == "day" else ten_god(day_stem, stem)
        pillar["ten_gods_branch"] = [ten_god(day_stem, s) for s in hidden]
        pillar["principal_ten_god"] = ten_god(day_stem, PRINCIPAL[branch])
    total = sum(counts.values())
    balance = {element: value / total for element, value in counts.items()}
    support = balance[day_element] + balance[resource]
    month_hidden = HIDDEN[pillars["month"]["branch"]]
    seasonal_support = sum(f for s, f in month_hidden.items() if stem_element(s) in {day_element, resource})
    root_strength = sum(item["fraction"] for item in roots) / len(pillars)
    visible_support = sum(stem_element(s) in {day_element, resource} for s in visible) / max(len(visible), 1)
    index = .45 * support + .25 * seasonal_support + .20 * root_strength + .10 * visible_support
    strength = "신강" if index >= .60 else "신약" if index <= .40 else "중화"
    candidates: dict[str, list[str]] = {
        "억부": [roles["resource"], roles["companion"]] if strength == "신약" else
                [roles["output"], roles["wealth"], roles["officer"]] if strength == "신강" else [],
        "조후": [], "통관": [], "병약": [],
    }
    month_branch = pillars["month"]["branch"]
    if month_branch in "巳午未":
        candidates["조후"] = ["water"]
    elif month_branch in "亥子丑":
        candidates["조후"] = ["fire"]
    for controller, controlled in CONTROLS.items():
        if balance[controller] >= .24 and balance[controlled] >= .24:
            candidates["통관"].append(GENERATES[controller])
    # Threshold is our conservative operational definition of 'excess', not in the source.
    for element in ELEMENTS:
        if balance[element] >= .40 and element not in candidates["억부"]:
            candidates["병약"].append(ELEMENTS[(ELEMENTS.index(element) - 2) % 5])
    avoid = [roles["wealth"], roles["officer"]] if strength == "신약" else [resource, day_element] if strength == "신강" else []
    votes = {element: .40 if element in avoid else .5 for element in ELEMENTS}
    weights = {"억부": .24, "조후": .18, "통관": .10, "병약": .06}
    for theory, elements in candidates.items():
        for element in set(elements):
            votes[element] += weights[theory]
    votes = {element: min(1.0, value) for element, value in votes.items()}
    favorable = sorted((e for e in ELEMENTS if votes[e] > .5), key=lambda e: (-votes[e], ELEMENTS.index(e)))
    # No evidence for a choice: do not pretend that missing elements MUST be useful.
    avoid = [roles["wealth"], roles["officer"]] if strength == "신약" else [resource, day_element] if strength == "신강" else []
    principal = PRINCIPAL[month_branch]
    principal_god = ten_god(day_stem, principal)
    blade = dict(zip(STEMS, "卯寅午巳午巳酉申子亥", strict=True))
    pattern_name = ("건록격 후보" if pillars["month"].get("growth_stage") == "건록" else
                    "양인격 후보" if month_branch == blade[day_stem] else
                    "비겁 월령: 정격 판정 유보" if principal_god in {"비견", "겁재"} else principal_god + "격 후보")
    special_uncertain = max(balance.values()) >= .60
    return {
        "balance": balance, "glyph_counts": {KO[e]: n for e, n in glyph_counts.items()},
        "strength": strength, "support_ratio": round(support, 5), "roles": roles,
        "favorable_elements": favorable, "avoid_elements": avoid,
        "strength_evidence": {"index": round(index, 5), "month_support": seasonal_support,
            "root_support": root_strength, "visible_support": visible_support,
            "rooted_stems": roots, "exposed_stems": exposed,
            "formula": ".45*support+.25*month+.20*roots+.10*visible",
            "thresholds": {"weak_max": .40, "strong_min": .60}, "basis": "자체 계량 규칙"},
        "ten_god_distribution": {g: round(v, 5) for g, v in gods.items()},
        "source_stars": source_stars(pillars, day_stem),
        "pattern": {"name": pattern_name, "principal_stem": principal, "principal_ten_god": principal_god,
            "exposed": principal in visible, "special_pattern_review_required": special_uncertain,
            "status": "후보: 종격·화격 및 합화 성립은 자동 확정하지 않음"},
        "useful_element_candidates": {theory: [KO[e] for e in elements] for theory, elements in candidates.items()},
        "element_preference": votes,
        "unresolved": ["용신 추정의 학파 차이", "亥의 戊23%는 제공 문서의 사령 비율 채택", "종격·화격 자동 확정 제외"],
    }


def evaluate_layers(natal: dict[str, Any], target: dict[str, Any], luck: dict[str, Any], preference: dict[str, float]) -> tuple[dict[str, Any], dict[str, float]]:
    """Keep DaYun/annual/month/day/hour relations and their actual score effects."""
    layers: dict[str, dict[str, Any]] = {}
    current = luck.get("current") or {}
    ganzhi = current.get("ganzhi", "")
    if len(ganzhi) == 2:
        layers["대운"] = {"ganzhi": ganzhi, "stem": ganzhi[0], "branch": ganzhi[1]}
    for key, label in (("year", "세운"), ("month", "월운"), ("day", "일진"), ("time", "시진")):
        if key in target:
            layers[label] = target[key]
    weights = {"대운": .30, "세운": .25, "월운": .20, "일진": .15, "시진": .10}
    aggregate = dict.fromkeys(ELEMENTS, 0.0)
    report: dict[str, Any] = {}
    total_weight = sum(weights[label] for label in layers)
    for label, pillar in layers.items():
        # Each layer is compared with natal plus the preceding larger time layer.
        source = {f"원국_{key}": p for key, p in natal.items()}
        previous = next(reversed(report), None) if report else None
        if previous:
            source[previous] = layers[previous]
        source[label] = pillar
        events = relations(source, required=label)
        affected = Counter()
        for event in events:
            if event["element"]:
                # A relation's symbol is not proof of actual transformation.
                affected[event["element"]] += .03
            else:
                for position in event["positions"]:
                    affected[stem_element(PRINCIPAL[source[position]["branch"]])] += .015
        energy = dict.fromkeys(ELEMENTS, 0.0)
        energy[stem_element(pillar["stem"])] += .5
        for stem, fraction in HIDDEN[pillar["branch"]].items():
            energy[stem_element(stem)] += .5 * fraction
        effects = {}
        for e in ELEMENTS:
            # Preference-relative effect: '합' is not universally good, '충' not universally bad.
            alignment = 2 * preference[e] - 1.0
            effects[e] = max(0.0, min(1.0, .5 + .25 * energy[e] * alignment + min(affected[e], .12) * alignment))
            aggregate[e] += weights[label] * effects[e] / total_weight
        report[label] = {"ganzhi": pillar["ganzhi"], "weight": weights[label] / total_weight,
            "relations": events, "element_scores": {KO[e]: round(v, 6) for e, v in effects.items()},
            "score_basis": "관계 존재·보완 후보 상대성에 따른 자체 가중치; 합화/길흉 확정 아님"}
    return report, aggregate


def source_stars(pillars: dict[str, Any], day_stem: str) -> list[dict[str, Any]]:
    """Only explicit source section 1.2.13 tables; explanatory, not predictive."""
    noble = dict(zip(STEMS, ("丑未", "子申", "亥酉", "亥酉", "丑未", "子申", "丑未", "寅午", "卯巳", "卯巳"), strict=True))
    scholar = dict(zip(STEMS, "巳午申酉申酉亥子寅卯", strict=True))
    blade = dict(zip(STEMS, "卯寅午巳午巳酉申子亥", strict=True))
    result = []
    def record(name: str, basis: str, targets: str) -> None:
        for position, pillar in pillars.items():
            if pillar["branch"] in targets:
                result.append({"name": name, "basis": basis, "position": position,
                               "branch": pillar["branch"], "used_for_number_score": False})
    for name, table in (("천을귀인", noble), ("문창귀인", scholar), ("양인", blade)):
        record(name, "일간", table[day_stem])
    groups = {"寅午戌": ("卯", "申", "戌"), "申子辰": ("酉", "寅", "辰"),
              "巳酉丑": ("午", "亥", "丑"), "亥卯未": ("子", "巳", "未")}
    for basis in ("year", "day"):
        for group, values in groups.items():
            if pillars[basis]["branch"] in group:
                for name, target in zip(("도화", "역마", "화개"), values, strict=True):
                    record(name, basis, target)
    partner = dict(zip(BRANCHES, "丑子未申巳辰亥寅卯戌酉午", strict=True))
    record("귀문관살", "일지", partner[pillars["day"]["branch"]])
    return result
